function M = calc_M_25_b(in1)
%calc_M_25_b
%    M = calc_M_25_b(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2026-06-27 15:55:17

th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th2);
t3 = cos(th3);
t4 = sin(th2);
t5 = sin(th3);
t6 = t2.^2;
t7 = t4.*(1.3e+1./2.0e+1);
t9 = t2.*t3.*t5.*(3.0./2.0e+1);
t8 = -t7;
M = reshape([t2.*(2.24e+2./5.0)+t6.*(3.37e+2./2.0e+1)-t3.^2.*t6.*(3.0./2.0e+1)+3.12e+2./5.0,t9,t8,t9,t5.^2.*(-3.0./2.0e+1)+1.83e+2./1.0e+1,0.0,t8,0.0,1.3e+1./2.0e+1],[3,3]);
end
