function C = calc_C_25_b(in1,in2)
%calc_C_25_b
%    C = calc_C_25_b(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2026-06-27 15:55:17

dth1 = in2(1,:);
dth2 = in2(2,:);
dth3 = in2(3,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th2);
t3 = cos(th3);
t4 = sin(th2);
t5 = sin(th3);
t6 = th3.*2.0;
t7 = t3.^2;
t8 = sin(t6);
t9 = (dth1.*t2)./4.0;
t11 = dth1.*t2.*t3.*t5.*3.0;
t12 = dth1.*t4.*(1.12e+2./5.0);
t14 = dth1.*t2.*t4.*(3.37e+2./2.0e+1);
t10 = dth2.*t7.*3.0;
t13 = dth2.*t8.*(3.0./4.0e+1);
t15 = dth1.*t2.*t7.*(3.0./2.0e+1);
t16 = dth3.*t2.*t7.*(3.0./2.0e+1);
t17 = t4.*t15;
C = reshape([-dth2.*(t4.*(1.12e+2./5.0)+t2.*t4.*(3.37e+2./2.0e+1)-t2.*t4.*t7.*(3.0./2.0e+1))+dth3.*t2.^2.*t3.*t5.*(3.0./2.0e+1),t12+t14+t16+(dth3.*t2)./4.0-dth1.*t2.*t4.*t7.*(3.0./2.0e+1),t2.*(dth2.*5.0+t10+t11).*(-1.0./2.0e+1),-t12-t14+t16+t17-dth3.*t2.*(2.0./5.0)-dth2.*t3.*t4.*t5.*(3.0./2.0e+1),dth3.*t8.*(-3.0./4.0e+1),-t9+t13-t15,(t2.*(dth2.*-8.0+t10+t11))./2.0e+1,t9-t13+t15,0.0],[3,3]);
end
