function N = calc_N_25_b(in1,in2)
%calc_N_25_b
%    N = calc_N_25_b(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2026-06-27 15:55:17

dth1 = in2(1,:);
dth2 = in2(2,:);
dth3 = in2(3,:);
th2 = in1(2,:);
N = [dth1.*(1.1e+1./1.0e+1);dth2.*(6.3e+1./1.0e+2)-cos(th2).*2.7468e+2;dth3.*(6.3e+1./1.0e+2)];
end
